# Generated by Django 5.2.2 on 2025-06-06 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_contratacao', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('mes', models.SmallIntegerField(verbose_name='Mes')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa', verbose_name='Pessoa')),
                ('salarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salario.salario', verbose_name='Salario')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='salario',
            field=models.ManyToManyField(through='pessoas.PessoaSalario', to='salario.salario'),
        ),
        migrations.AddConstraint(
            model_name='pessoasalario',
            constraint=models.UniqueConstraint(fields=('pessoa', 'ano', 'mes'), name='unique_salario_mensal'),
        ),
    ]
