# Generated by Django 5.2 on 2025-06-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_cargo_departamento_alter_pessoa_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='valor_salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
