# Generated by Django 5.2.2 on 2025-06-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoasalario_ano'),
        ('salario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoasalario',
            name='salarios',
        ),
        migrations.AddField(
            model_name='pessoasalario',
            name='salario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salario.salario', verbose_name='Salário'),
            preserve_default=False,
        ),
    ]
