# Generated by Django 5.2.2 on 2025-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('anos_trabalho', models.PositiveSmallIntegerField(verbose_name=' Anos de trabalho')),
            ],
        ),
    ]
