# Generated by Django 5.2 on 2025-06-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
