# Generated by Django 5.2 on 2025-06-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_cargo_departamento_alter_pessoa_cargo_and_more'),
        ('salario', '0002_alter_salario_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='pessoa',
            field=models.ManyToManyField(to='pessoas.pessoa'),
        ),
    ]
