# Generated by Django 5.2 on 2025-06-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salario', '0003_salario_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salario',
            old_name='valor',
            new_name='salario',
        ),
    ]
